#!/bin/sh

case "$(uname -m)" in
  x86_64) ARCH=x86_64 ;;
  *) echo "Package for $(uname -m) architecture is not available." ; exit 1 ;;
esac

LATEST=$(curl -s https://api.github.com/repos/DetachHead/rebased/releases/latest | grep '"tag_name"' | head -1 | cut -d'"' -f4 | sed 's/^v//')
CURRENT=$(ls /var/log/packages/ 2>/dev/null | grep "^rebased-" | cut -d"-" -f3)

if [ -n "$LATEST" ] && [ "x$LATEST" != "x$CURRENT" ]; then
    BUILD="1"
    TAG="_auto"
    PKGNAM=$(basename $0 -updater)
    VERSION=${LATEST}
    ( cd /usr/share/doc/rebased-${CURRENT}/SlackBuild \
      && source ./rebased.SlackBuild \
      && /sbin/upgradepkg /tmp/rebased-$LATEST-$ARCH-$BUILD$TAG.txz \
      && rm -f /tmp/rebased.tar.gz
    )
fi
