#!/bin/sh

RELEASE=${RELEASE:-stable}    # stable, beta, or unstable
case "$(uname -m)" in
  x86_64) DEBARCH="amd64" ; LIBDIRSUFFIX="64" ; ARCH=x86_64 ;;
  *) echo "Package for $(uname -m) architecture is not available." ; exit 1 ;;
esac

set -e

LATEST=$(curl http://dl.google.com/linux/deb/dists/$RELEASE/main/binary-$DEBARCH/Packages 2>/dev/null |grep "google-chrome-$RELEASE$" -n1|grep Version|cut -d" " -f2|cut -d"-" -f1)
CURRENT=$(ls /var/log/packages/ -1|grep google-chrome|cut -d"-" -f3)

if [ "x$LATEST" != "x$CURRENT" ]; then
    BUILD="1"
    TAG="_auto"
    PKGNAM=$(basename $0 -updater)
    VERSION=${LATEST}
    ( cd /usr/share/doc/google-chrome-${CURRENT}/SlackBuild \
      && source ./google-chrome.SlackBuild \
      && /sbin/upgradepkg /tmp/google-chrome-$LATEST-$ARCH-$BUILD$TAG.txz \
      && cd /usr/share/doc/google-chrome/SlackBuild \
      && rm $(basename `ls google-chrome-${RELEASE}_*_${DEBARCH}.deb`)
    )
fi