#!/bin/sh

# Slackware build script for tpm2_requirements

# Copyright 2026 MiRacLe.RPZ <miracle@rpz.name>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ''AS IS'' AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

PRGNAM=tpm2_requirements
PKGNAM=${PKGNAM:-$(basename $0 .SlackBuild)}

VERSION=${VERSION:-1.1}
BUILD=${BUILD:-3}
TAG=${TAG:-_rpz}
PKGTYPE=${PKGTYPE:-txz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ "$ARCH" = "i486" ] || [ "$ARCH" = "i686" ]; then
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  LIBDIRSUFFIX="64"
else
  LIBDIRSUFFIX=""
fi

CWD=$(pwd)
TMP=${TMP:-/tmp/$(whoami)}
PKG=$TMP/package-$PKGNAM
OUTPUT=${OUTPUT:-/tmp}

set -eu

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT

# Install udev rules
mkdir -p $PKG/lib/udev/rules.d
cat $CWD/70-tpm2-udev.rules > $PKG/lib/udev/rules.d/70-tpm2-udev.rules

# Install requirements checker
mkdir -p $PKG/usr/bin
cat $CWD/tpm2_check_requirements > $PKG/usr/bin/tpm2_check_requirements
chmod 755 $PKG/usr/bin/tpm2_check_requirements

# Install doinst.sh
mkdir -p $PKG/install
cat $CWD/doinst.sh > $PKG/install/doinst.sh

# NOT Install OpenSSL config for pkcs11-provider + tpm2-pkcs11
# Install OpenSSL config for tpm2-pkcs11
mkdir -p $PKG/etc/ssl
sed "s|@LIBDIRSUFFIX@|${LIBDIRSUFFIX}|g" $CWD/openssl_tpm.cnf.in > $PKG/etc/ssl/openssl_tpm.cnf
chmod 644 $PKG/etc/ssl/openssl_tpm.cnf

# Install slack-desc
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-$VERSION-noarch-$BUILD$TAG.${PKGTYPE}
